### ISSUE TITLE
Can't find GATEWAY_PRINCIPAL value in the lib.rs file

### ISSUE THREAD

**Issue by Darkwing4** [omnia-network/ic_websocket_example#1]
Can't complete final locally running step from main repo page.

![image](https://github.com/omnia-network/ic_websocket_example/assets/22674637/5806e70a-b740-4e7a-8826-d552459a9d54)

Should i just return it, it will be work?

**Comment by ilbertt** [comment]
Since **v0.3.1** versions of the SDKs, the gateway principal is not needed anymore in the initialization, see the [changelog](https://forum.dfinity.org/t/ic-websocket-stable-release/23872/31) too.

---

> Can't complete final locally running step from main repo page.

Can you please report here the errors that you're having?

> Should i just return it, it will be work?

Can you please be more explicit on what you mean here?

**Comment by Darkwing4** [comment]
Hi, @ilbertt!

I'm working on deploying a local IC Gateway and trying to integrate it with your WebSocket example. I'm curious if I need to specify the GATEWAY_PRINCIPAL of my local IC Gateway somewhere within the code. I found a reference to it in the CanisterWsOpenArguments constructor parameters. However, being new to Rust (only a couple of weeks in), I'm finding it challenging to understand exactly where and if I need to set the GATEWAY_PRINCIPAL. Could you please guide me on the necessary steps to get your example working with a local version of the IC Gateway?

Thank you for your fast assistance.

**Comment by Darkwing4** [comment]
So I just can't complete this step

![image](https://github.com/omnia-network/ic_websocket_example/assets/22674637/29a0ad53-f39b-4ae1-8b5d-6a6f73baa2e7)

**Comment by Darkwing4** [comment]
Additionally, I'm encountering an error during deployment:

~/ic_websocket_example$ dfx deploy
Deploying all canisters.
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to deploy canisters.
Failed to construct wallet canister caller: Certificate is stale (over 240s). Is the computer's clock synchronized?

Is this issue related to the GATEWAY_PRINCIPAL, or could there be another cause? Any advice on resolving this would be greatly appreciated.

**Comment by Darkwing4** [comment]
sudo ntpdate time.nist.gov not work for me.
I use WSL 2

**Comment by ilbertt** [comment]
> I'm working on deploying a local IC Gateway and trying to integrate it with your WebSocket example. I'm curious if I need to specify the GATEWAY_PRINCIPAL of my local IC Gateway somewhere within the code. I found a reference to it in the CanisterWsOpenArguments constructor parameters. However, being new to Rust (only a couple of weeks in), I'm finding it challenging to understand exactly where and if I need to set the GATEWAY_PRINCIPAL. Could you please guide me on the necessary steps to get your example working with a local version of the IC Gateway?

You don't need the gateway principal anymore in your application. I've updated the README accordingly.

To run this example locally:
1. in a separate folder and terminal, run the IC WS Gateway by cloning the [ic-websocket-gateway](https://github.com/omnia-network/ic-websocket-gateway) repo and running:
   ```bash
   cargo run
   ```
   Have a look at the [IC WebSocket Gateway's README Standalone](https://github.com/omnia-network/ic-websocket-gateway#standalone) section.
   If you'd rather use Docker, there's also a [Docker](https://github.com/omnia-network/ic-websocket-gateway#docker) section.
2. in this example, comment the lines: https://github.com/omnia-network/ic_websocket_example/blob/b017614a35530687a8908c105eaf81a8228fc078/src/ic_websocket_example_frontend/src/main.ts#L12-L20 and **uncomment** the lines: https://github.com/omnia-network/ic_websocket_example/blob/b017614a35530687a8908c105eaf81a8228fc078/src/ic_websocket_example_frontend/src/main.ts#L22-L25
3. start a local replica:
    ```bash
    dfx start --clean
    ```
5. deploy the example canisters:
    ```bash
    dfx deploy
    ```
6. open the frontend in a browser following the link printed at the end of the output of the previous command.

**Comment by ilbertt** [comment]
> Additionally, I'm encountering an error during deployment:
> 
> ~/ic_websocket_example$ dfx deploy Deploying all canisters. Error: Failed while trying to deploy canisters. Caused by: Failed while trying to deploy canisters. Failed to construct wallet canister caller: Certificate is stale (over 240s). Is the computer's clock synchronized?
> 
> Is this issue related to the GATEWAY_PRINCIPAL, or could there be another cause?

This issue doesn't seem related to the IC WebSocket protocol. Have you tried restarting the local replica and deploying the canisters with:
```bash
dfx deploy --no-wallet
```
instead?

> Any advice on resolving this would be greatly appreciated.

The [forum](https://forum.dfinity.org/) is usually a good place where to find technical assistance. I've briefly looked into it to find a thread with an issue similar to yours, but I didn't find anything relevant. If the error persists, I'd suggest you to open a new discussion there.

**Comment by Darkwing4** [comment]
```
dfx start --clean
dfx deploy --no-wallet
```

clean start and no wallet flag fixed my problem, thx

**Comment by ilbertt** [comment]
Closing this issue.

@Darkwing4 feel free to re-open it or open a new one if you still have any problems.
